"""
Generate notebooks/06_phase3_cross_arch.ipynb
Phase 3: Cross-Architecture Validation of AEIoU on Kvasir-SEG
"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def code_cell(source):
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {}, 'outputs': [], 'source': source}

def md_cell(source):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': source}

cells = []

# ── 0. Title ─────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "# 06 \u00b7 Phase 3: Cross-Architecture Validation of AEIoU\n\n"
    "**Research question:** Does AEIoU outperform EIoU regardless of detector architecture?\n\n"
    "| Architecture | Type | Framework |\n"
    "|---|---|---|\n"
    "| YOLOv26s | One-stage anchor-free | Ultralytics |\n"
    "| RT-DETR-L | Transformer end-to-end | Ultralytics |\n"
    "| Faster R-CNN R50-FPN | Two-stage anchor-based | MMDetection |\n\n"
    "**Key output:** Cross-architecture table (rows=arch, cols=loss, cells=mAP50-95).  \n"
    "If AEIoU beats EIoU on \u22652 of 3 architectures, the gain is loss-driven, not architecture-specific.\n\n"
    "**Setup (Kaggle):**\n"
    "- Accelerator: GPU T4 x2 | Internet: On\n"
    "- Secret: `WANDB_API_KEY` (optional)\n\n"
    "**Setup (Colab):**\n"
    "- Runtime: GPU (T4 or A100) | Mount Drive for persistence"
))

# ── 1. Environment detection ─────────────────────────────────────────────────
cells.append(md_cell("## Section 1 \u00b7 Environment Setup"))

cells.append(code_cell(
    "# --- Detect runtime environment (Kaggle vs Colab vs local)\n"
    "import os, sys\n"
    "from pathlib import Path\n\n"
    "ON_KAGGLE = os.path.exists('/kaggle/working')\n"
    "ON_COLAB  = 'google.colab' in sys.modules or os.path.exists('/content')\n\n"
    "if ON_KAGGLE:\n"
    "    ROOT = Path('/kaggle/working')\n"
    "    print('Runtime: Kaggle')\n"
    "elif ON_COLAB:\n"
    "    ROOT = Path('/content')\n"
    "    print('Runtime: Colab')\n"
    "else:\n"
    "    ROOT = Path.cwd()\n"
    "    print(f'Runtime: local ({ROOT})')\n\n"
    "import os as _os\n"
    "gpu = _os.popen('nvidia-smi --query-gpu=name --format=csv,noheader').read().strip()\n"
    "print(f'GPU: {gpu if gpu else \"none detected\"}')\n"
))

cells.append(code_cell(
    "# --- Install dependencies\n"
    "import subprocess, sys\n\n"
    "# ultralytics 8.4.9: confirmed working with yolo26n/s/rtdetr and our monkey-patch\n"
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',\n"
    "                'ultralytics==8.4.9', 'wandb==0.24.1', 'pycocotools'], check=True)\n\n"
    "# MMDetection for Faster R-CNN\n"
    "# Installed separately in Section 7 to avoid conflicts with ultralytics\n"
    "print('Core dependencies installed.')\n"
))

cells.append(code_cell(
    "# --- Clone repo (idempotent)\n"
    "import os, sys\n"
    "from pathlib import Path\n\n"
    "REPO_PATH = ROOT / 'amorphous-yolo'\n"
    "if not (REPO_PATH / '.git').exists():\n"
    "    os.system(f'git clone https://github.com/nipun-taneja/amorphous-yolo.git {REPO_PATH}')\n"
    "    print('Cloned.')\n"
    "else:\n"
    "    os.system(f'git -C {REPO_PATH} pull --ff-only')\n"
    "    print('Repo up to date.')\n\n"
    "if str(REPO_PATH) not in sys.path:\n"
    "    sys.path.insert(0, str(REPO_PATH))\n"
    "print(f'Repo: {REPO_PATH}')\n"
))

# ── 2. WandB ─────────────────────────────────────────────────────────────────
cells.append(code_cell(
    "# --- WandB setup\n"
    "import os, wandb\n\n"
    "WANDB_PROJECT = 'amorphous-yolo-phase3'\n\n"
    "if ON_KAGGLE:\n"
    "    try:\n"
    "        from kaggle_secrets import UserSecretsClient\n"
    "        _key = UserSecretsClient().get_secret('WANDB_API_KEY')\n"
    "        if _key: os.environ['WANDB_API_KEY'] = _key\n"
    "    except Exception:\n"
    "        pass\n"
    "elif ON_COLAB:\n"
    "    try:\n"
    "        from google.colab import userdata\n"
    "        _key = userdata.get('WANDB_API_KEY')\n"
    "        if _key: os.environ['WANDB_API_KEY'] = _key\n"
    "    except Exception:\n"
    "        pass\n\n"
    "if os.environ.get('WANDB_API_KEY'):\n"
    "    wandb.login(key=os.environ['WANDB_API_KEY'], relogin=True)\n"
    "    print(f'WandB active. Project: {WANDB_PROJECT}')\n"
    "else:\n"
    "    os.environ['WANDB_MODE'] = 'disabled'\n"
    "    print('WandB disabled (no API key). Training runs normally.')\n"
))

# ── 3. Constants ─────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 2 \u00b7 Constants & Loss Configs"))

cells.append(code_cell(
    "# --- Phase 3 constants\n"
    "import math, time, json as _json\n"
    "from pathlib import Path\n"
    "from datetime import datetime\n\n"
    "PROJECT_DIR   = ROOT / 'amorphous-yolo'\n"
    "DATASET_ROOT  = PROJECT_DIR / 'datasets' / 'kvasir-seg'\n\n"
    "# Phase 3 experiments go in a separate dir to avoid collision with Phase 2\n"
    "EXPERIMENTS   = PROJECT_DIR / 'experiments_phase3'\n"
    "ANALYSIS_DIR  = EXPERIMENTS / 'analysis'\n"
    "METRICS_DIR   = EXPERIMENTS / 'metrics'\n"
    "MANIFEST_PATH = EXPERIMENTS / 'manifest.json'\n"
    "for _d in [EXPERIMENTS, ANALYSIS_DIR, METRICS_DIR]:\n"
    "    _d.mkdir(parents=True, exist_ok=True)\n\n"
    "# Drive persistence (Colab only)\n"
    "DRIVE_AVAILABLE = False\n"
    "DRIVE_EXPERIMENTS = Path('/content/drive/MyDrive/amorphous_yolo/experiments_phase3')\n\n"
    "# Training\n"
    "EPOCHS = 20\n"
    "IMGSZ  = 640\n"
    "DEVICE = 0\n"
    "SEEDS  = [42]\n\n"
    "# Dataset splits\n"
    "SPLIT_CONFIGS = {\n"
    "    'clean': PROJECT_DIR / 'data' / 'kvasir_seg.yaml',\n"
    "    'low':   PROJECT_DIR / 'data' / 'kvasir_seg_low.yaml',\n"
    "    'high':  PROJECT_DIR / 'data' / 'kvasir_seg_high.yaml',\n"
    "}\n\n"
    "def _fmt_r(r): return str(r).replace('.', 'p')\n\n"
    "PALETTE = {\n"
    "    'ciou': '#DDA15E', 'eiou': '#E63946', 'eciou': '#9B2226',\n"
    "    'aeiou_r0p1': '#023E8A', 'aeiou_r0p2': '#0077B6', 'aeiou_r0p3': '#00B4D8',\n"
    "    'aeiou_r0p4': '#48CAE4', 'aeiou_r0p5': '#90E0EF', 'aeiou_r0p6': '#2A9D8F',\n"
    "    'aeiou_r0p7': '#52B788', 'aeiou_r0p8': '#74C69D', 'aeiou_r0p9': '#95D5B2',\n"
    "    'aeiou_r1p0': '#6A4C93',\n"
    "}\n"
    "LOSS_LABELS = {'ciou': 'CIoU', 'eiou': 'EIoU', 'eciou': 'ECIoU'}\n"
    "for r in [round(x*0.1,1) for x in range(1,11)]:\n"
    "    LOSS_LABELS[f'aeiou_r{_fmt_r(r)}'] = f'AEIoU \u03bb={r}'\n\n"
    "print('Constants loaded.')\n"
    "print(f'Experiments dir: {EXPERIMENTS}')\n"
))

cells.append(code_cell(
    "# --- Select Phase 3 loss configs\n"
    "# Try to load best 3 AEIoU lambdas from Phase 2 (nb03) results.\n"
    "# Falls back to [0.1, 0.3, 0.5] if Phase 2 results not available.\n"
    "import numpy as np\n\n"
    "PHASE2_SUMMARY = PROJECT_DIR / 'experiments_kvasir' / 'metrics_all_losses.json'\n\n"
    "def _pick_best_aeiou_lambdas(n=3):\n"
    "    if not PHASE2_SUMMARY.exists():\n"
    "        print('[WARN] Phase 2 metrics not found. Using default lambdas [0.1, 0.3, 0.5].')\n"
    "        return [0.1, 0.3, 0.5]\n"
    "    data = _json.loads(PHASE2_SUMMARY.read_text())\n"
    "    aeiou = {}\n"
    "    for run, m in data.items():\n"
    "        if m.get('loss', '').startswith('aeiou') and m.get('split') == 'clean':\n"
    "            r = float(m['loss'].split('_r')[1].replace('p', '.'))\n"
    "            aeiou[r] = m.get('map50_95', 0) or 0\n"
    "    if not aeiou:\n"
    "        return [0.1, 0.3, 0.5]\n"
    "    top = sorted(aeiou, key=aeiou.get, reverse=True)[:n]\n"
    "    top_sorted = sorted(top)\n"
    "    print(f'Best {n} AEIoU lambdas from Phase 2: {top_sorted}')\n"
    "    for lam in top_sorted:\n"
    "        print(f'  lambda={lam}: mAP50-95={aeiou[lam]:.4f}')\n"
    "    return top_sorted\n\n"
    "BEST_LAMBDAS = _pick_best_aeiou_lambdas(n=3)\n\n"
    "# Phase 3 loss configs: best 3 AEIoU + EIoU + CIoU (Ultralytics default) + ECIoU\n"
    "PHASE3_AEIOU_KEYS    = [f'aeiou_r{_fmt_r(r)}' for r in BEST_LAMBDAS]\n"
    "PHASE3_BASELINE_KEYS = ['ciou', 'eiou', 'eciou']\n"
    "PHASE3_LOSS_KEYS     = PHASE3_BASELINE_KEYS + PHASE3_AEIOU_KEYS\n\n"
    "print(f'\\nPhase 3 loss configs ({len(PHASE3_LOSS_KEYS)}):')\n"
    "for k in PHASE3_LOSS_KEYS:\n"
    "    print(f'  {k}: {LOSS_LABELS.get(k, k)}')\n"
))

# ── 4. Dataset ────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 3 \u00b7 Kvasir-SEG Dataset"))

cells.append(code_cell(
    "# --- Download Kvasir-SEG (idempotent)\n"
    "import zipfile, urllib.request, ssl\n\n"
    "kvasir_zip = PROJECT_DIR / 'datasets' / 'kvasir-seg.zip'\n"
    "images_dir = DATASET_ROOT / 'images'\n\n"
    "if images_dir.exists() and len(list(images_dir.glob('*.jpg'))) > 900:\n"
    "    print(f'Kvasir-SEG already present ({len(list(images_dir.glob(\"*.jpg\")))} images).')\n"
    "else:\n"
    "    print('Downloading Kvasir-SEG (~44 MB)...')\n"
    "    (PROJECT_DIR / 'datasets').mkdir(parents=True, exist_ok=True)\n"
    "    ssl_ctx = ssl._create_unverified_context()\n"
    "    with urllib.request.urlopen(\n"
    "        'https://datasets.simula.no/downloads/kvasir-seg.zip',\n"
    "        context=ssl_ctx\n"
    "    ) as r, open(kvasir_zip, 'wb') as f:\n"
    "        f.write(r.read())\n"
    "    with zipfile.ZipFile(kvasir_zip) as z:\n"
    "        z.extractall(PROJECT_DIR / 'datasets')\n"
    "    print('Download complete.')\n"
))

cells.append(code_cell(
    "# --- Convert masks -> YOLO labels + 80/20 split (idempotent)\n"
    "# Reuses the same conversion logic as notebook 03.\n"
    "import cv2, numpy as np, random, shutil\n\n"
    "TRAIN_DIR = DATASET_ROOT / 'train'\n"
    "VALID_DIR = DATASET_ROOT / 'valid'\n\n"
    "if (TRAIN_DIR / 'labels').exists() and len(list((TRAIN_DIR / 'labels').glob('*.txt'))) > 700:\n"
    "    print('Labels already generated.')\n"
    "else:\n"
    "    print('Generating YOLO labels from masks...')\n"
    "    masks_dir = DATASET_ROOT / 'masks'\n"
    "    for split_dir in [TRAIN_DIR, VALID_DIR]:\n"
    "        (split_dir / 'images').mkdir(parents=True, exist_ok=True)\n"
    "        (split_dir / 'labels').mkdir(parents=True, exist_ok=True)\n\n"
    "    all_imgs = sorted((DATASET_ROOT / 'images').glob('*.jpg'))\n"
    "    random.seed(42)\n"
    "    random.shuffle(all_imgs)\n"
    "    n_val = int(len(all_imgs) * 0.2)\n"
    "    val_set = set(p.stem for p in all_imgs[:n_val])\n\n"
    "    def _mask_to_bbox(mask_path):\n"
    "        m = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)\n"
    "        if m is None: return None\n"
    "        _, bw = cv2.threshold(m, 127, 255, cv2.THRESH_BINARY)\n"
    "        cnts, _ = cv2.findContours(bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n"
    "        if not cnts: return None\n"
    "        x,y,w,h = cv2.boundingRect(max(cnts, key=cv2.contourArea))\n"
    "        H, W = m.shape\n"
    "        return (x+w/2)/W, (y+h/2)/H, w/W, h/H\n\n"
    "    for img_path in all_imgs:\n"
    "        bbox = _mask_to_bbox(masks_dir / img_path.name.replace('.jpg', '.jpg'))\n"
    "        if bbox is None: continue\n"
    "        split_dir = VALID_DIR if img_path.stem in val_set else TRAIN_DIR\n"
    "        shutil.copy2(img_path, split_dir / 'images' / img_path.name)\n"
    "        lbl = split_dir / 'labels' / f'{img_path.stem}.txt'\n"
    "        lbl.write_text(f'0 {bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}\\n')\n\n"
    "    n_tr = len(list((TRAIN_DIR/'labels').glob('*.txt')))\n"
    "    n_vl = len(list((VALID_DIR/'labels').glob('*.txt')))\n"
    "    print(f'Done: {n_tr} train, {n_vl} val labels.')\n"
))

cells.append(code_cell(
    "# --- Build noise-perturbed val splits (idempotent)\n"
    "# Reuses src/nbbox_noise.py from the repo.\n"
    "import sys\n"
    "sys.path.insert(0, str(PROJECT_DIR))\n"
    "from src.nbbox_noise import perturb_labels\n\n"
    "LOW_DIR  = DATASET_ROOT / 'valid_low'\n"
    "HIGH_DIR = DATASET_ROOT / 'valid_high'\n\n"
    "for out_dir, sigma in [(LOW_DIR, 0.02), (HIGH_DIR, 0.08)]:\n"
    "    if (out_dir / 'labels').exists() and len(list((out_dir/'labels').glob('*.txt'))) > 150:\n"
    "        print(f'{out_dir.name}: already exists.')\n"
    "        continue\n"
    "    (out_dir / 'images').mkdir(parents=True, exist_ok=True)\n"
    "    (out_dir / 'labels').mkdir(parents=True, exist_ok=True)\n"
    "    import shutil\n"
    "    for p in (VALID_DIR / 'images').glob('*.jpg'):\n"
    "        shutil.copy2(p, out_dir / 'images' / p.name)\n"
    "    perturb_labels(VALID_DIR / 'labels', out_dir / 'labels', sigma=sigma, seed=42)\n"
    "    print(f'{out_dir.name}: sigma={sigma} done.')\n\n"
    "# Verify split YAMLs exist\n"
    "for split_name, yaml_path in SPLIT_CONFIGS.items():\n"
    "    status = 'OK' if yaml_path.exists() else 'MISSING'\n"
    "    print(f'  {split_name}: {yaml_path.name} [{status}]')\n"
))

# ── 5. Monkey-patch ───────────────────────────────────────────────────────────
cells.append(md_cell("## Section 4 \u00b7 Monkey-Patch Infrastructure"))

cells.append(code_cell(
    "# --- BboxLoss monkey-patch (same pattern as notebook 03)\n"
    "# Replaces the IoU term in Ultralytics BboxLoss.forward with any custom loss.\n"
    "# Works for YOLOv26s and RT-DETR-L (both use BboxLoss internally).\n"
    "import types, torch, torch.nn.functional as F\n"
    "import ultralytics.utils.loss as loss_mod\n\n"
    "_ORIGINAL_BBOX_FORWARD = loss_mod.BboxLoss.forward\n\n"
    "def _make_bbox_forward(loss_fn):\n"
    "    def bbox_loss_forward(\n"
    "        self, pred_dist, pred_bboxes, anchor_points,\n"
    "        target_bboxes, target_scores, target_scores_sum, fg_mask, imgsz, stride,\n"
    "    ):\n"
    "        weight = target_scores.sum(-1)[fg_mask].unsqueeze(-1)\n"
    "        per_box = loss_fn(pred_bboxes[fg_mask], target_bboxes[fg_mask])\n"
    "        loss_iou = (per_box.unsqueeze(-1) * weight).sum() / target_scores_sum\n"
    "        if self.dfl_loss:\n"
    "            target_ltrb = loss_mod.bbox2dist(\n"
    "                anchor_points, target_bboxes, self.dfl_loss.reg_max - 1)\n"
    "            loss_dfl = self.dfl_loss(\n"
    "                pred_dist[fg_mask].view(-1, self.dfl_loss.reg_max),\n"
    "                target_ltrb[fg_mask],\n"
    "            ) * weight\n"
    "            loss_dfl = loss_dfl.sum() / target_scores_sum\n"
    "        else:\n"
    "            target_ltrb = loss_mod.bbox2dist(anchor_points, target_bboxes)\n"
    "            target_ltrb = target_ltrb * stride\n"
    "            target_ltrb[..., 0::2] /= imgsz[1]; target_ltrb[..., 1::2] /= imgsz[0]\n"
    "            pred_dist_s = pred_dist * stride\n"
    "            pred_dist_s[..., 0::2] /= imgsz[1]; pred_dist_s[..., 1::2] /= imgsz[0]\n"
    "            loss_dfl = (\n"
    "                F.l1_loss(pred_dist_s[fg_mask], target_ltrb[fg_mask],\n"
    "                          reduction='none').mean(-1, keepdim=True) * weight\n"
    "            ).sum() / target_scores_sum\n"
    "        return loss_iou, loss_dfl\n"
    "    return bbox_loss_forward\n\n"
    "def patch_loss(loss_fn):\n"
    "    loss_mod.BboxLoss.forward = _make_bbox_forward(loss_fn)\n"
    "    tag = f'(lambda={loss_fn.rigidity})' if hasattr(loss_fn, 'rigidity') else ''\n"
    "    print(f'  [PATCH] BboxLoss -> {type(loss_fn).__name__}{tag}')\n\n"
    "def restore_loss():\n"
    "    loss_mod.BboxLoss.forward = _ORIGINAL_BBOX_FORWARD\n\n"
    "print('Monkey-patch infrastructure ready.')\n"
))

cells.append(code_cell(
    "# --- Verify patch round-trip\n"
    "from src.losses import EIoULoss\n"
    "patch_loss(EIoULoss(reduction='none'))\n"
    "assert loss_mod.BboxLoss.forward is not _ORIGINAL_BBOX_FORWARD, 'Patch failed'\n"
    "restore_loss()\n"
    "assert loss_mod.BboxLoss.forward is _ORIGINAL_BBOX_FORWARD, 'Restore failed'\n"
    "print('Patch round-trip: OK')\n"
))

# ── 6. Loss registry ─────────────────────────────────────────────────────────
cells.append(md_cell("## Section 5 \u00b7 Loss Registry"))

cells.append(code_cell(
    "# --- Build Phase 3 loss registry from PHASE3_LOSS_KEYS\n"
    "from src.losses import CIoULoss, EIoULoss, ECIoULoss, AEIoULoss\n\n"
    "_BASE_CLS = {'ciou': CIoULoss, 'eiou': EIoULoss, 'eciou': ECIoULoss}\n\n"
    "LOSS_REGISTRY = {}\n"
    "for k in PHASE3_LOSS_KEYS:\n"
    "    if k in _BASE_CLS:\n"
    "        LOSS_REGISTRY[k] = _BASE_CLS[k](reduction='none')\n"
    "    elif k.startswith('aeiou_r'):\n"
    "        r = float(k.split('_r')[1].replace('p', '.'))\n"
    "        LOSS_REGISTRY[k] = AEIoULoss(rigidity=r, reduction='none')\n\n"
    "print(f'Loss registry ({len(LOSS_REGISTRY)} configs):')\n"
    "for name, fn in LOSS_REGISTRY.items():\n"
    "    tag = f' rigidity={fn.rigidity}' if hasattr(fn, 'rigidity') else ''\n"
    "    print(f'  {name}: {type(fn).__name__}{tag}')\n"
))

# ── 7. Training infrastructure ────────────────────────────────────────────────
cells.append(md_cell("## Section 6 \u00b7 Training Infrastructure"))

cells.append(code_cell(
    "# --- Drive mount (Colab only)\n"
    "if ON_COLAB:\n"
    "    try:\n"
    "        from google.colab import drive\n"
    "        drive.mount('/content/drive', force_remount=False)\n"
    "        DRIVE_EXPERIMENTS.mkdir(parents=True, exist_ok=True)\n"
    "        DRIVE_AVAILABLE = True\n"
    "        print(f'Drive mounted. Backup: {DRIVE_EXPERIMENTS}')\n"
    "    except Exception as e:\n"
    "        print(f'Drive unavailable: {e}')\n"
    "else:\n"
    "    print('Kaggle: Drive not used. Outputs auto-saved to /kaggle/working/')\n"
))

cells.append(code_cell(
    "# --- run_training(): shared across all three architectures\n"
    "# arch_prefix controls the run name: 'yolo26s', 'rtdetr', 'frcnn'\n"
    "import json as _json, shutil, time\n"
    "from pathlib import Path as _Path\n"
    "from datetime import datetime\n"
    "from ultralytics import YOLO\n\n"
    "def _load_manifest():\n"
    "    return _json.loads(MANIFEST_PATH.read_text()) if MANIFEST_PATH.exists() else {}\n\n"
    "def _write_manifest(run_name, meta):\n"
    "    m = _load_manifest(); m[run_name] = meta\n"
    "    MANIFEST_PATH.write_text(_json.dumps(m, indent=2))\n\n"
    "def _sync_to_drive(run_name):\n"
    "    if not DRIVE_AVAILABLE: return\n"
    "    try:\n"
    "        shutil.copytree(str(EXPERIMENTS / run_name),\n"
    "                        str(DRIVE_EXPERIMENTS / run_name), dirs_exist_ok=True)\n"
    "    except Exception as e:\n"
    "        print(f'  [DRIVE] {e}')\n\n"
    "def run_training(arch_prefix, model_pt, loss_name, loss_fn,\n"
    "                 split_name, yaml_path, seed=42, epochs=None, device=None):\n"
    "    epochs = epochs or EPOCHS\n"
    "    device = device if device is not None else DEVICE\n"
    "    run_name = f'phase3_{arch_prefix}_{loss_name}_{split_name}_s{seed}_e{epochs}'\n"
    "    run_dir  = EXPERIMENTS / run_name\n\n"
    "    if (run_dir / 'results.csv').exists():\n"
    "        print(f'[SKIP] {run_name}'); return run_dir\n\n"
    "    local_last = run_dir / 'weights' / 'last.pt'\n"
    "    resuming   = local_last.exists()\n\n"
    "    sep = '=' * 65\n"
    "    tag = '[RESUME]' if resuming else '[START]'\n"
    "    print(f'\\n{sep}\\n{tag} {run_name}\\n{sep}')\n\n"
    "    meta = {'arch': arch_prefix, 'loss': loss_name, 'split': split_name,\n"
    "            'seed': seed, 'epochs': epochs,\n"
    "            'rigidity': float(getattr(loss_fn, 'rigidity', -1) or -1),\n"
    "            'timestamp': datetime.now().isoformat(), 'status': 'running'}\n"
    "    _write_manifest(run_name, meta)\n"
    "    t0 = time.time()\n"
    "    try:\n"
    "        import os as _os\n"
    "        _os.environ.update({'WANDB_PROJECT': WANDB_PROJECT,\n"
    "                            'WANDB_NAME': run_name, 'WANDB_TAGS': f'{arch_prefix},{loss_name}'})\n"
    "        patch_loss(loss_fn)\n"
    "        if resuming:\n"
    "            model = YOLO(str(local_last))\n"
    "            results = model.train(resume=True)\n"
    "        else:\n"
    "            model = YOLO(model_pt)\n"
    "            results = model.train(\n"
    "                data=str(yaml_path), epochs=epochs, imgsz=IMGSZ,\n"
    "                project=str(EXPERIMENTS), name=run_name,\n"
    "                device=device, seed=seed, exist_ok=True,\n"
    "            )\n"
    "        meta['status'] = 'complete'\n"
    "        meta['elapsed_sec'] = round(time.time() - t0, 1)\n"
    "        try:\n"
    "            import wandb as _w\n"
    "            if _w.run: _w.finish()\n"
    "        except Exception: pass\n"
    "    except Exception as e:\n"
    "        print(f'  [ERROR] {e}'); meta['status'] = 'failed'; meta['error'] = str(e); raise\n"
    "    finally:\n"
    "        restore_loss(); _write_manifest(run_name, meta); _sync_to_drive(run_name)\n"
    "    print(f'[DONE] {run_name}  ({meta.get(\"elapsed_sec\", 0):.0f}s)')\n"
    "    return run_dir\n\n"
    "print('run_training() ready.')\n"
))

# ── 8. YOLOv26s ──────────────────────────────────────────────────────────────
cells.append(md_cell(
    "## Section 7 \u00b7 YOLOv26s Runs\n\n"
    "Same one-stage anchor-free family as Phase 2 (YOLOv26n), but Small variant.  \n"
    "Validates that AEIoU gains hold when scaling up within the YOLO family.  \n"
    "Identical monkey-patch — no integration changes needed.\n\n"
    "| Runs | Time (T4) |\n"
    "|---|---|\n"
    f"| 6 losses \u00d7 3 splits \u00d7 1 seed = 18 | ~2 hrs |"
))

cells.append(code_cell(
    "# --- YOLOv26s: 6 loss configs x 3 splits x 1 seed\n"
    "YOLO26S_PT = 'yolo26s.pt'\n\n"
    "for loss_name, loss_fn in LOSS_REGISTRY.items():\n"
    "    for split_name, yaml_path in SPLIT_CONFIGS.items():\n"
    "        for seed in SEEDS:\n"
    "            run_training(\n"
    "                arch_prefix='yolo26s',\n"
    "                model_pt=YOLO26S_PT,\n"
    "                loss_name=loss_name,\n"
    "                loss_fn=loss_fn,\n"
    "                split_name=split_name,\n"
    "                yaml_path=yaml_path,\n"
    "                seed=seed,\n"
    "            )\n"
    "restore_loss()\n"
    "print('YOLOv26s runs complete.')\n"
))

# ── 9. RT-DETR-L ─────────────────────────────────────────────────────────────
cells.append(md_cell(
    "## Section 8 \u00b7 RT-DETR-L Runs\n\n"
    "Transformer-based end-to-end detector (Zhao et al., 2023). Ultralytics native support.  \n"
    "RT-DETR uses Hungarian matching + GIoU by default. In Ultralytics 8.x, the box  \n"
    "regression branch routes through the same `BboxLoss` class — same monkey-patch applies.\n\n"
    "The verification cell below confirms this before any training runs.\n\n"
    "| Runs | Time (T4) |\n"
    "|---|---|\n"
    f"| 6 losses \u00d7 3 splits \u00d7 1 seed = 18 | ~4 hrs |"
))

cells.append(code_cell(
    "# --- Verify BboxLoss patch works for RT-DETR\n"
    "# RT-DETR in Ultralytics uses RTDETRDetectionLoss which internally\n"
    "# instantiates BboxLoss — so our class-level patch applies automatically.\n"
    "import ultralytics.utils.loss as _lm\n\n"
    "# Check RT-DETR loss module imports BboxLoss\n"
    "try:\n"
    "    import ultralytics.models.rtdetr.train as _rtdet_train\n"
    "    import inspect\n"
    "    src = inspect.getsource(_rtdet_train)\n"
    "    uses_bboxloss = 'BboxLoss' in src\n"
    "    print(f'RTDETRDetectionLoss uses BboxLoss: {uses_bboxloss}')\n"
    "    if not uses_bboxloss:\n"
    "        print('[WARN] BboxLoss not found in RT-DETR train module.')\n"
    "        print('       Check ultralytics/models/rtdetr/ for the loss entrypoint.')\n"
    "        print('       Runs will still execute -- verify loss values decrease normally.')\n"
    "except Exception as e:\n"
    "    print(f'Could not inspect RT-DETR source: {e}')\n"
    "    print('Proceeding -- patch is applied class-wide regardless.')\n\n"
    "# Smoke test: 1 epoch to confirm loss decreases\n"
    "from src.losses import EIoULoss\n"
    "_smoke_name = f'phase3_rtdetr_eiou_clean_s42_smoke'\n"
    "_smoke_dir  = EXPERIMENTS / _smoke_name\n"
    "if not (_smoke_dir / 'results.csv').exists():\n"
    "    print('Running 1-epoch smoke test for RT-DETR...')\n"
    "    run_training('rtdetr', 'rtdetr-l.pt', 'eiou', EIoULoss(reduction='none'),\n"
    "                 'clean', SPLIT_CONFIGS['clean'], seed=42, epochs=1)\n"
    "    restore_loss()\n"
    "    # Read final box_loss\n"
    "    import pandas as pd\n"
    "    _df = pd.read_csv(_smoke_dir / 'results.csv')\n"
    "    _df.columns = _df.columns.str.strip()\n"
    "    _loss_col = [c for c in _df.columns if 'box_loss' in c]\n"
    "    if _loss_col:\n"
    "        print(f'Smoke test box_loss: {_df[_loss_col[0]].iloc[-1]:.4f} (should be > 0)')\n"
    "    print('RT-DETR smoke test: PASSED')\n"
    "else:\n"
    "    print('RT-DETR smoke test already run.')\n"
))

cells.append(code_cell(
    "# --- RT-DETR-L: 6 loss configs x 3 splits x 1 seed\n"
    "RTDETR_PT = 'rtdetr-l.pt'\n\n"
    "for loss_name, loss_fn in LOSS_REGISTRY.items():\n"
    "    for split_name, yaml_path in SPLIT_CONFIGS.items():\n"
    "        for seed in SEEDS:\n"
    "            run_training(\n"
    "                arch_prefix='rtdetr',\n"
    "                model_pt=RTDETR_PT,\n"
    "                loss_name=loss_name,\n"
    "                loss_fn=loss_fn,\n"
    "                split_name=split_name,\n"
    "                yaml_path=yaml_path,\n"
    "                seed=seed,\n"
    "            )\n"
    "restore_loss()\n"
    "print('RT-DETR-L runs complete.')\n"
))

# ── 10. Faster R-CNN ─────────────────────────────────────────────────────────
cells.append(md_cell(
    "## Section 9 \u00b7 Faster R-CNN R50-FPN Runs (MMDetection)\n\n"
    "> **Note:** MMDetection is installed in a separate step to avoid dependency\n"
    "> conflicts with Ultralytics. Run this section in a **fresh Kaggle session**\n"
    "> (or a separate Colab runtime) after Sections 7 and 8 are complete.\n\n"
    "Integration steps:\n"
    "1. Install MMDetection + register `AEIoULossMMDet`\n"
    "2. Convert Kvasir-SEG YOLO labels to COCO JSON\n"
    "3. Build one config per loss, train, collect results\n\n"
    "**Fallback:** If MMDetection setup fails, substitute FCOS (same MMDet, simpler config,\n"
    "no RPN) — the key requirement is a non-YOLO architecture."
))

cells.append(code_cell(
    "# --- Install MMDetection (run in a fresh session to avoid conflicts)\n"
    "import subprocess, sys\n\n"
    "def _run(cmd):\n"
    "    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)\n"
    "    if r.returncode != 0:\n"
    "        print(f'FAILED: {cmd}\\n{r.stderr[-500:]}')\n"
    "    return r.returncode == 0\n\n"
    "print('Installing MMDetection dependencies...')\n"
    "_run('pip install -q openmim')\n"
    "_run('mim install mmengine mmcv mmdet -q')\n"
    "print('MMDetection installed.')\n\n"
    "# Verify\n"
    "try:\n"
    "    import mmdet\n"
    "    print(f'mmdet version: {mmdet.__version__}')\n"
    "except ImportError as e:\n"
    "    print(f'[ERROR] mmdet import failed: {e}')\n"
    "    print('Try running in a fresh session or use the FCOS fallback below.')\n"
))

cells.append(code_cell(
    "# --- Register AEIoULossMMDet in MMDetection loss registry\n"
    "# Thin wrapper that calls our existing AEIoULoss with the MMDet calling convention.\n"
    "import torch, torch.nn as nn\n"
    "from mmdet.registry import MODELS\n"
    "from src.losses import AEIoULoss as _AEIoU, EIoULoss as _EIoU, CIoULoss as _CIoU, ECIoULoss as _ECIoU\n\n"
    "def _make_mmdet_loss(loss_cls, **kwargs):\n"
    "    \"\"\"Factory: wraps a src/losses.py class for MMDetection's loss API.\"\"\"\n"
    "    _reduction = kwargs.pop('reduction', 'none')\n"
    "    _loss_weight = kwargs.pop('loss_weight', 1.0)\n"
    "    _inner = loss_cls(reduction='none', **kwargs)\n\n"
    "    @MODELS.register_module(name=f'{loss_cls.__name__}MMDet', force=True)\n"
    "    class _Wrapped(nn.Module):\n"
    "        def __init__(self): super().__init__()\n"
    "        def forward(self, pred, target, weight=None, avg_factor=None, **kw):\n"
    "            loss = _inner(pred, target)\n"
    "            if weight is not None: loss = loss * weight\n"
    "            if avg_factor is not None: return loss.sum() / avg_factor\n"
    "            return loss.mean()\n"
    "    return _Wrapped\n\n"
    "AEIoULossMMDet  = {r: _make_mmdet_loss(_AEIoU, rigidity=r)\n"
    "                   for r in BEST_LAMBDAS}\n"
    "EIoULossMMDet   = _make_mmdet_loss(_EIoU)\n"
    "CIoULossMMDet   = _make_mmdet_loss(_CIoU)\n"
    "ECIoULossMMDet  = _make_mmdet_loss(_ECIoU)\n\n"
    "print('MMDet loss classes registered.')\n"
    "print('Registered:', [f'{c.__name__}' for c in\n"
    "      list(AEIoULossMMDet.values()) + [EIoULossMMDet, CIoULossMMDet, ECIoULossMMDet]])\n"
))

cells.append(code_cell(
    "# --- Convert Kvasir-SEG val labels to COCO JSON (for MMDetection DataLoader)\n"
    "import cv2, json as _json\n\n"
    "def _yolo_to_coco_json(img_dir, lbl_dir, out_path, split_name='val'):\n"
    "    if out_path.exists(): print(f'  {out_path.name}: exists.'); return\n"
    "    images, anns, ann_id = [], [], 1\n"
    "    for img_path in sorted(img_dir.glob('*.jpg')):\n"
    "        img = cv2.imread(str(img_path))\n"
    "        H, W = img.shape[:2]\n"
    "        stem = img_path.stem\n"
    "        img_id = abs(hash(stem)) % (10**7)\n"
    "        images.append({'id': img_id, 'file_name': img_path.name, 'width': W, 'height': H})\n"
    "        lbl = lbl_dir / f'{stem}.txt'\n"
    "        if not lbl.exists(): continue\n"
    "        for line in lbl.read_text().strip().splitlines():\n"
    "            if not line.strip(): continue\n"
    "            _, cx, cy, bw, bh = map(float, line.split())\n"
    "            x1, y1 = (cx-bw/2)*W, (cy-bh/2)*H\n"
    "            anns.append({'id': ann_id, 'image_id': img_id, 'category_id': 1,\n"
    "                         'bbox': [x1, y1, bw*W, bh*H], 'area': bw*W*bh*H, 'iscrowd': 0})\n"
    "            ann_id += 1\n"
    "    coco = {'images': images, 'annotations': anns,\n"
    "            'categories': [{'id': 1, 'name': 'polyp'}]}\n"
    "    out_path.write_text(_json.dumps(coco))\n"
    "    print(f'  {out_path.name}: {len(images)} images, {len(anns)} annotations.')\n\n"
    "COCO_ANNO_DIR = DATASET_ROOT / 'coco_annotations'\n"
    "COCO_ANNO_DIR.mkdir(exist_ok=True)\n\n"
    "for split_name, src_lbl in [\n"
    "    ('train', TRAIN_DIR / 'labels'),\n"
    "    ('val',   VALID_DIR / 'labels'),\n"
    "    ('val_low',  LOW_DIR  / 'labels'),\n"
    "    ('val_high', HIGH_DIR / 'labels'),\n"
    "]:\n"
    "    img_dir = (TRAIN_DIR if split_name=='train' else VALID_DIR) / 'images'\n"
    "    if 'low' in split_name: img_dir = LOW_DIR / 'images'\n"
    "    if 'high' in split_name: img_dir = HIGH_DIR / 'images'\n"
    "    _yolo_to_coco_json(img_dir, src_lbl, COCO_ANNO_DIR / f'instances_{split_name}.json')\n"
))

cells.append(code_cell(
    "# --- Build MMDetection config for Faster R-CNN with a given loss\n"
    "from mmengine.config import Config\n\n"
    "MMDET_BASE_CFG = 'faster-rcnn_r50_fpn_1x_coco'  # MMDet model zoo name\n\n"
    "def build_frcnn_config(loss_mmdet_name, rigidity=None, out_path=None):\n"
    "    \"\"\"Create a Faster R-CNN config with custom box loss in both RPN + R-CNN head.\"\"\"\n"
    "    cfg = Config.fromfile(f'configs/faster_rcnn/{MMDET_BASE_CFG}.py')\n\n"
    "    loss_dict = {'type': loss_mmdet_name, 'loss_weight': 1.0}\n"
    "    if rigidity is not None:\n"
    "        loss_dict['rigidity'] = rigidity\n\n"
    "    # Override dataset to Kvasir-SEG COCO format\n"
    "    cfg.data_root = str(DATASET_ROOT)\n"
    "    cfg.metainfo = {'classes': ('polyp',), 'palette': [(220, 20, 60)]}\n"
    "    for split, ann_file in [\n"
    "        ('train', 'coco_annotations/instances_train.json'),\n"
    "        ('val',   'coco_annotations/instances_val.json'),\n"
    "    ]:\n"
    "        cfg.train_dataloader.dataset.ann_file = str(DATASET_ROOT / ann_file)\n"
    "        cfg.train_dataloader.dataset.data_prefix = {'img': str(TRAIN_DIR / 'images')}\n"
    "        cfg.val_dataloader.dataset.ann_file = str(DATASET_ROOT / 'coco_annotations/instances_val.json')\n"
    "        cfg.val_dataloader.dataset.data_prefix = {'img': str(VALID_DIR / 'images')}\n"
    "        cfg.val_evaluator.ann_file = str(DATASET_ROOT / 'coco_annotations/instances_val.json')\n\n"
    "    # Override number of classes\n"
    "    cfg.model.roi_head.bbox_head.num_classes = 1\n"
    "    cfg.model.rpn_head.num_classes = 1\n\n"
    "    # Override box loss in both heads\n"
    "    cfg.model.rpn_head.loss_bbox = loss_dict.copy()\n"
    "    cfg.model.roi_head.bbox_head.loss_bbox = loss_dict.copy()\n\n"
    "    # Training schedule\n"
    "    cfg.train_cfg.max_epochs = EPOCHS\n"
    "    cfg.default_hooks.checkpoint.interval = EPOCHS\n"
    "    cfg.default_hooks.logger.interval = 50\n\n"
    "    if out_path:\n"
    "        out_path.write_text(cfg.pretty_text)\n"
    "    return cfg\n\n"
    "print('build_frcnn_config() ready.')\n"
))

cells.append(code_cell(
    "# --- run_frcnn(): train one Faster R-CNN run via MMDetection Runner\n"
    "from mmengine.runner import Runner\n\n"
    "FRCNN_CONFIGS_DIR = EXPERIMENTS / 'frcnn_configs'\n"
    "FRCNN_CONFIGS_DIR.mkdir(exist_ok=True)\n\n"
    "def run_frcnn(loss_name, loss_mmdet_name, rigidity=None, split_name='clean', seed=42):\n"
    "    run_name = f'phase3_frcnn_{loss_name}_{split_name}_s{seed}_e{EPOCHS}'\n"
    "    run_dir  = EXPERIMENTS / run_name\n"
    "    result_json = run_dir / 'metric.json'\n\n"
    "    if result_json.exists():\n"
    "        print(f'[SKIP] {run_name}'); return run_dir\n\n"
    "    run_dir.mkdir(exist_ok=True)\n"
    "    print(f'\\n{\"=\"*65}\\n[START] {run_name}\\n{\"=\"*65}')\n\n"
    "    # Use correct val annotation for noise splits\n"
    "    ann_suffix = {'clean': 'val', 'low': 'val_low', 'high': 'val_high'}[split_name]\n"
    "    val_img    = {'clean': VALID_DIR, 'low': LOW_DIR, 'high': HIGH_DIR}[split_name]\n\n"
    "    cfg = build_frcnn_config(loss_mmdet_name, rigidity=rigidity)\n"
    "    cfg.val_dataloader.dataset.ann_file = str(\n"
    "        DATASET_ROOT / f'coco_annotations/instances_{ann_suffix}.json')\n"
    "    cfg.val_dataloader.dataset.data_prefix = {'img': str(val_img / 'images')}\n"
    "    cfg.val_evaluator.ann_file = str(\n"
    "        DATASET_ROOT / f'coco_annotations/instances_{ann_suffix}.json')\n"
    "    cfg.work_dir  = str(run_dir)\n"
    "    cfg.seed      = seed\n"
    "    cfg.randomness = {'seed': seed}\n\n"
    "    runner = Runner.from_cfg(cfg)\n"
    "    runner.train()\n\n"
    "    # Persist final metric\n"
    "    import json as _j\n"
    "    metrics = runner.val()\n"
    "    result_json.write_text(_j.dumps(metrics, indent=2))\n"
    "    _sync_to_drive(run_name)\n"
    "    print(f'[DONE] {run_name}')\n"
    "    return run_dir\n\n"
    "print('run_frcnn() ready.')\n"
))

cells.append(code_cell(
    "# --- Faster R-CNN: 6 loss configs x 3 splits x 1 seed\n"
    "_FRCNN_LOSS_MAP = {\n"
    "    'ciou':  ('CIoULossMMDet',  None),\n"
    "    'eiou':  ('EIoULossMMDet',  None),\n"
    "    'eciou': ('ECIoULossMMDet', None),\n"
    "}\n"
    "for r in BEST_LAMBDAS:\n"
    "    k = f'aeiou_r{_fmt_r(r)}'\n"
    "    _FRCNN_LOSS_MAP[k] = (f'AEIoULossMMDet_{_fmt_r(r)}', r)\n\n"
    "for loss_name in PHASE3_LOSS_KEYS:\n"
    "    mmdet_name, rig = _FRCNN_LOSS_MAP[loss_name]\n"
    "    for split_name in SPLIT_CONFIGS:\n"
    "        for seed in SEEDS:\n"
    "            try:\n"
    "                run_frcnn(loss_name, mmdet_name, rigidity=rig,\n"
    "                          split_name=split_name, seed=seed)\n"
    "            except Exception as e:\n"
    "                print(f'  [ERROR] frcnn {loss_name} {split_name}: {e}')\n\n"
    "print('Faster R-CNN runs complete (or failed gracefully).')\n"
))

# ── 11. Results collection ────────────────────────────────────────────────────
cells.append(md_cell("## Section 10 \u00b7 Results Collection"))

cells.append(code_cell(
    "# --- Load results from all three architectures into one DataFrame\n"
    "import pandas as pd, numpy as np, json as _json\n\n"
    "MAP50_COL = 'metrics/mAP50(B)'\n"
    "MAP95_COL = 'metrics/mAP50-95(B)'\n\n"
    "_ARCHS = ['yolo26s', 'rtdetr', 'frcnn']\n"
    "_arch_labels = {'yolo26s': 'YOLOv26s', 'rtdetr': 'RT-DETR-L', 'frcnn': 'Faster R-CNN'}\n\n"
    "def _load_run_metrics(run_dir):\n"
    "    \"\"\"Extract final mAP50 and mAP50-95 from a completed run directory.\"\"\"\n"
    "    # Ultralytics: results.csv\n"
    "    csv = run_dir / 'results.csv'\n"
    "    if csv.exists():\n"
    "        df = pd.read_csv(csv)\n"
    "        df.columns = df.columns.str.strip()\n"
    "        last = df.iloc[-1]\n"
    "        return {\n"
    "            'map50':   float(last.get(MAP50_COL, 0) or 0),\n"
    "            'map50_95': float(last.get(MAP95_COL, 0) or 0),\n"
    "        }\n"
    "    # MMDetection: metric.json\n"
    "    mj = run_dir / 'metric.json'\n"
    "    if mj.exists():\n"
    "        m = _json.loads(mj.read_text())\n"
    "        return {\n"
    "            'map50':    float(m.get('coco/bbox_mAP_50', m.get('bbox_mAP_50', 0))),\n"
    "            'map50_95': float(m.get('coco/bbox_mAP',   m.get('bbox_mAP',   0))),\n"
    "        }\n"
    "    return None\n\n"
    "rows = []\n"
    "for arch in _ARCHS:\n"
    "    for loss_name in PHASE3_LOSS_KEYS:\n"
    "        for split_name in SPLIT_CONFIGS:\n"
    "            for seed in SEEDS:\n"
    "                run_name = f'phase3_{arch}_{loss_name}_{split_name}_s{seed}_e{EPOCHS}'\n"
    "                run_dir  = EXPERIMENTS / run_name\n"
    "                m = _load_run_metrics(run_dir)\n"
    "                rows.append({\n"
    "                    'arch': arch, 'loss': loss_name, 'split': split_name,\n"
    "                    'seed': seed, 'run': run_name,\n"
    "                    'map50':    m['map50']    if m else None,\n"
    "                    'map50_95': m['map50_95'] if m else None,\n"
    "                    'rigidity': float(loss_name.split('_r')[1].replace('p','.')) if 'aeiou' in loss_name else -1.0,\n"
    "                })\n\n"
    "df_all = pd.DataFrame(rows)\n"
    "df_all.to_csv(EXPERIMENTS / 'phase3_all_results.csv', index=False)\n\n"
    "n_complete = df_all['map50_95'].notna().sum()\n"
    "print(f'Results loaded: {n_complete}/{len(df_all)} runs complete.')\n"
    "print(df_all.groupby(['arch','split'])['map50_95'].count().to_string())\n"
))

# ── 12. Cross-architecture table ──────────────────────────────────────────────
cells.append(md_cell(
    "## Section 11 \u00b7 Cross-Architecture Table\n\n"
    "**Key deliverable for reviewers.** Shows that AEIoU improvement is consistent  \n"
    "across architectures — not an artifact of YOLOv26 specifically."
))

cells.append(code_cell(
    "# --- Cross-architecture table: rows=arch, cols=loss, cells=mAP50-95 (clean split)\n"
    "import pandas as pd, numpy as np\n"
    "import matplotlib.pyplot as plt, seaborn as sns\n\n"
    "_clean = df_all[df_all['split'] == 'clean'].copy()\n"
    "_pivot = _clean.pivot_table(index='arch', columns='loss',\n"
    "                             values='map50_95', aggfunc='mean')\n"
    "_pivot = _pivot.reindex(index=_ARCHS, columns=PHASE3_LOSS_KEYS)\n"
    "_pivot.index = [_arch_labels[a] for a in _ARCHS]\n"
    "_pivot.columns = [LOSS_LABELS.get(c, c) for c in PHASE3_LOSS_KEYS]\n\n"
    "# Delta vs EIoU column\n"
    "_eiou_col = LOSS_LABELS.get('eiou', 'EIoU')\n"
    "for c in _pivot.columns:\n"
    "    if 'AEIoU' in c:\n"
    "        _pivot[f'\\u0394 {c}'] = _pivot[c] - _pivot[_eiou_col]\n\n"
    "print('=== Cross-Architecture Table: mAP50-95 (clean split) ===')\n"
    "print(_pivot.round(4).to_string())\n"
    "_pivot.to_csv(ANALYSIS_DIR / 'cross_arch_table.csv')\n\n"
    "# ── Heatmap ──────────────────────────────────────────────────────────────\n"
    "_base_cols = [LOSS_LABELS.get(k,k) for k in PHASE3_LOSS_KEYS]\n"
    "_heat = _pivot[_base_cols].copy()\n\n"
    "fig, ax = plt.subplots(figsize=(12, 3.5))\n"
    "sns.heatmap(_heat.astype(float), ax=ax,\n"
    "            annot=True, fmt='.4f', annot_kws={'size': 10},\n"
    "            cmap='YlGn', linewidths=0.5, linecolor='#ccc',\n"
    "            cbar_kws={'label': 'mAP50-95'})\n"
    "ax.set_title('Cross-Architecture mAP50-95 — clean split', fontsize=13, fontweight='bold')\n"
    "ax.set_xlabel('Loss function', fontsize=11)\n"
    "ax.set_ylabel('Architecture', fontsize=11)\n"
    "plt.tight_layout()\n"
    "_save = ANALYSIS_DIR / 'cross_arch_heatmap.png'\n"
    "plt.savefig(_save, dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved -> {_save}')\n"
))

cells.append(code_cell(
    "# --- Delta table: AEIoU gain over EIoU per architecture\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n\n"
    "_aeiou_cols_raw = [k for k in PHASE3_LOSS_KEYS if 'aeiou' in k]\n"
    "_aeiou_labels   = [LOSS_LABELS.get(k, k) for k in _aeiou_cols_raw]\n"
    "_eiou_col_raw   = 'eiou'\n\n"
    "_clean = df_all[df_all['split'] == 'clean']\n"
    "_delta_rows = []\n"
    "for arch in _ARCHS:\n"
    "    sub = _clean[_clean['arch'] == arch]\n"
    "    eiou_map = sub[sub['loss'] == _eiou_col_raw]['map50_95'].mean()\n"
    "    for lam_key in _aeiou_cols_raw:\n"
    "        aeiou_map = sub[sub['loss'] == lam_key]['map50_95'].mean()\n"
    "        _delta_rows.append({\n"
    "            'Architecture': _arch_labels[arch],\n"
    "            'Loss': LOSS_LABELS.get(lam_key, lam_key),\n"
    "            'EIoU mAP50-95': round(eiou_map, 4) if not np.isnan(eiou_map) else None,\n"
    "            'AEIoU mAP50-95': round(aeiou_map, 4) if not np.isnan(aeiou_map) else None,\n"
    "            'Delta': round(aeiou_map - eiou_map, 4) if (not np.isnan(eiou_map) and not np.isnan(aeiou_map)) else None,\n"
    "        })\n\n"
    "df_delta = pd.DataFrame(_delta_rows)\n"
    "print('=== AEIoU vs EIoU delta (mAP50-95, clean split) ===')\n"
    "print(df_delta.to_string(index=False))\n"
    "df_delta.to_csv(ANALYSIS_DIR / 'aeiou_vs_eiou_delta.csv', index=False)\n\n"
    "# ── Bar chart: delta per arch x AEIoU lambda ─────────────────────────────\n"
    "fig, ax = plt.subplots(figsize=(10, 5))\n"
    "_arch_list = [_arch_labels[a] for a in _ARCHS]\n"
    "_x = np.arange(len(_arch_list))\n"
    "_w = 0.25\n"
    "_colors = ['#023E8A', '#00B4D8', '#2A9D8F'][:len(_aeiou_cols_raw)]\n"
    "for j, (lam_key, lam_label) in enumerate(zip(_aeiou_cols_raw, _aeiou_labels)):\n"
    "    deltas = []\n"
    "    for arch in _ARCHS:\n"
    "        row = df_delta[(df_delta['Architecture'] == _arch_labels[arch]) &\n"
    "                       (df_delta['Loss'] == lam_label)]\n"
    "        deltas.append(row['Delta'].iloc[0] if not row.empty and row['Delta'].iloc[0] is not None else 0)\n"
    "    bars = ax.bar(_x + j*_w, deltas, _w, label=lam_label,\n"
    "                  color=_colors[j % len(_colors)], alpha=0.85)\n"
    "    for bar, d in zip(bars, deltas):\n"
    "        if d is not None and abs(d) > 0.001:\n"
    "            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,\n"
    "                    f'{d:+.3f}', ha='center', va='bottom', fontsize=8)\n\n"
    "ax.axhline(0, color='black', lw=0.8, ls='--')\n"
    "ax.set_xticks(_x + _w)\n"
    "ax.set_xticklabels(_arch_list, fontsize=11)\n"
    "ax.set_ylabel('mAP50-95 delta vs EIoU', fontsize=11)\n"
    "ax.set_title('AEIoU gain over EIoU by architecture (clean split)', fontsize=13, fontweight='bold')\n"
    "ax.legend(fontsize=10)\n"
    "ax.grid(axis='y', alpha=0.3)\n"
    "plt.tight_layout()\n"
    "_save = ANALYSIS_DIR / 'aeiou_delta_by_arch.png'\n"
    "plt.savefig(_save, dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved -> {_save}')\n"
))

cells.append(code_cell(
    "# --- Success criteria check\n"
    "print('=== Phase 3 Success Criteria ===')\n"
    "_results = []\n"
    "for arch in _ARCHS:\n"
    "    sub = df_all[(df_all['arch'] == arch) & (df_all['split'] == 'clean')]\n"
    "    eiou_map = sub[sub['loss'] == 'eiou']['map50_95'].mean()\n"
    "    best_aeiou_map = sub[sub['loss'].str.startswith('aeiou')]['map50_95'].max()\n"
    "    if not (isinstance(eiou_map, float) and isinstance(best_aeiou_map, float)): continue\n"
    "    delta = best_aeiou_map - eiou_map\n"
    "    passed = delta > 0\n"
    "    _results.append(passed)\n"
    "    mark = 'PASS' if passed else 'FAIL'\n"
    "    print(f'  [{mark}] {_arch_labels[arch]:15s}: EIoU={eiou_map:.4f}  '\n"
    "          f'best AEIoU={best_aeiou_map:.4f}  delta={delta:+.4f}')\n\n"
    "n_pass = sum(_results)\n"
    "print(f'\\nAEIoU > EIoU on {n_pass}/{len(_results)} architectures')\n"
    "if n_pass >= 2:\n"
    "    print('SUCCESS: gain is consistent across architectures.')\n"
    "else:\n"
    "    print('REVIEW: gain not consistent. Investigate per-arch results.')\n"
))

# ── 13. PR curves + COCO AP per arch ─────────────────────────────────────────
cells.append(md_cell("## Section 12 \u00b7 PR Curves & COCO AP Suite per Architecture"))

cells.append(code_cell(
    "# --- Compute and persist metrics for all Phase 3 Ultralytics runs\n"
    "# (yolo26s + rtdetr -- Faster R-CNN metrics come from MMDet's own evaluator)\n"
    "import json as _json\n"
    "import numpy as np\n"
    "from pycocotools.coco import COCO\n"
    "from pycocotools.cocoeval import COCOeval\n"
    "from ultralytics import YOLO\n\n"
    "COCO_GT_JSON = DATASET_ROOT / 'valid' / 'coco_gt.json'\n\n"
    "# Build COCO GT JSON if not present\n"
    "if not COCO_GT_JSON.exists():\n"
    "    import cv2\n"
    "    _imgs, _anns, _aid = [], [], 1\n"
    "    for _ip in sorted((VALID_DIR/'images').glob('*.jpg')):\n"
    "        _img = cv2.imread(str(_ip)); H,W = _img.shape[:2]\n"
    "        _iid = abs(hash(_ip.stem)) % (10**7)\n"
    "        _imgs.append({'id':_iid,'file_name':_ip.name,'width':W,'height':H})\n"
    "        _lbl = VALID_DIR/'labels'/f'{_ip.stem}.txt'\n"
    "        if not _lbl.exists(): continue\n"
    "        for _ln in _lbl.read_text().strip().splitlines():\n"
    "            _,cx,cy,bw,bh = map(float,_ln.split())\n"
    "            x1,y1 = (cx-bw/2)*W,(cy-bh/2)*H\n"
    "            _anns.append({'id':_aid,'image_id':_iid,'category_id':1,\n"
    "                          'bbox':[x1,y1,bw*W,bh*H],'area':bw*W*bh*H,'iscrowd':0})\n"
    "            _aid += 1\n"
    "    COCO_GT_JSON.parent.mkdir(parents=True, exist_ok=True)\n"
    "    COCO_GT_JSON.write_text(_json.dumps({'images':_imgs,'annotations':_anns,\n"
    "                                         'categories':[{'id':1,'name':'polyp'}]}))\n"
    "    print(f'COCO GT JSON built: {len(_imgs)} imgs, {len(_anns)} anns')\n"
    "else:\n"
    "    print(f'COCO GT JSON exists: {COCO_GT_JSON}')\n"
))

cells.append(code_cell(
    "# --- compute_metrics_ultralytics(): persist PR + COCO AP for one run\n"
    "def compute_metrics_ultralytics(run_name, weights_path, yaml_path, force=False):\n"
    "    out_dir = METRICS_DIR / run_name\n"
    "    if (out_dir / 'coco_ap_suite.json').exists() and not force:\n"
    "        print(f'  [SKIP] {run_name}'); return\n"
    "    if not Path(weights_path).exists():\n"
    "        print(f'  [MISS] {weights_path}'); return\n"
    "    out_dir.mkdir(exist_ok=True)\n"
    "    model = YOLO(str(weights_path))\n"
    "    val_res = model.val(data=str(yaml_path), verbose=False,\n"
    "                        save_json=True, conf=0.001, iou=0.6)\n\n"
    "    # PR curve\n"
    "    try:\n"
    "        prec = np.array(val_res.box.p).reshape(-1).tolist()\n"
    "        rec  = np.array(val_res.box.r).reshape(-1).tolist()\n"
    "        f1   = np.array(val_res.box.f1).reshape(-1).tolist()\n"
    "    except Exception: prec,rec,f1 = [],[],[]\n"
    "    pr = {'precision':prec,'recall':rec,'f1':f1,\n"
    "          'ap50':float(val_res.box.map50),'ap75':float(val_res.box.map75),\n"
    "          'map50_95':float(val_res.box.map),\n"
    "          'ap_per_iou_threshold':val_res.box.maps.tolist(),\n"
    "          'iou_thresholds':np.round(np.arange(0.5,1.0,0.05),2).tolist()}\n"
    "    (out_dir/'pr_curve.json').write_text(_json.dumps(pr,indent=2))\n\n"
    "    # COCO AP suite\n"
    "    suite = {'map50_95':float(val_res.box.map),'map50':float(val_res.box.map50),\n"
    "             'map75':float(val_res.box.map75),\n"
    "             'APs':None,'APm':None,'APl':None,'AR_100':None}\n"
    "    pred_candidates = list(Path(str(val_res.save_dir)).glob('*predictions*.json'))\n"
    "    if pred_candidates:\n"
    "        try:\n"
    "            import io, contextlib\n"
    "            coco_gt = COCO(str(COCO_GT_JSON))\n"
    "            coco_dt = coco_gt.loadRes(str(pred_candidates[0]))\n"
    "            ev = COCOeval(coco_gt, coco_dt, 'bbox')\n"
    "            buf = io.StringIO()\n"
    "            with contextlib.redirect_stdout(buf):\n"
    "                ev.evaluate(); ev.accumulate(); ev.summarize()\n"
    "            s = ev.stats\n"
    "            suite.update({'map50_95':float(s[0]),'map50':float(s[1]),'map75':float(s[2]),\n"
    "                          'APs':float(s[3]),'APm':float(s[4]),'APl':float(s[5]),'AR_100':float(s[8])})\n"
    "        except Exception as e:\n"
    "            print(f'  [WARN] pycocotools: {e}')\n"
    "    (out_dir/'coco_ap_suite.json').write_text(_json.dumps(suite,indent=2))\n\n"
    "    # Confusion matrix\n"
    "    cm_out = {}\n"
    "    try:\n"
    "        cm = model.validator.metrics.confusion_matrix\n"
    "        mat = cm.matrix.tolist()\n"
    "        cm_out = {'matrix':mat,'class_names':['polyp'],\n"
    "                  'TP':mat[0][0],'FN':mat[0][1] if len(mat[0])>1 else None,\n"
    "                  'FP':mat[1][0] if len(mat)>1 else None}\n"
    "    except Exception as e:\n"
    "        cm_out = {'error':str(e)}\n"
    "    (out_dir/'confusion_matrix.json').write_text(_json.dumps(cm_out,indent=2))\n"
    "    print(f'  [DONE] {run_name}  '\n"
    "          f'mAP={suite[\"map50_95\"]:.4f} APs={suite[\"APs\"]} APm={suite[\"APm\"]} APl={suite[\"APl\"]}')\n\n"
    "# Run for all completed Ultralytics runs\n"
    "for arch in ['yolo26s', 'rtdetr']:\n"
    "    for loss_name in PHASE3_LOSS_KEYS:\n"
    "        for split_name, yaml_path in SPLIT_CONFIGS.items():\n"
    "            for seed in SEEDS:\n"
    "                run_name = f'phase3_{arch}_{loss_name}_{split_name}_s{seed}_e{EPOCHS}'\n"
    "                weights  = EXPERIMENTS / run_name / 'weights' / 'best.pt'\n"
    "                compute_metrics_ultralytics(run_name, weights, yaml_path)\n\n"
    "print('Metrics extraction complete.')\n"
))

cells.append(code_cell(
    "# --- PR curves per architecture (clean split)\n"
    "import json as _json, numpy as np, matplotlib.pyplot as plt, matplotlib.lines as mlines\n\n"
    "_iou_thresh = np.round(np.arange(0.5, 1.0, 0.05), 2)\n\n"
    "for arch in ['yolo26s', 'rtdetr']:  # frcnn uses MMDet evaluator, no PR JSON\n"
    "    fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=True)\n"
    "    fig.suptitle(f'PR Curves — {_arch_labels[arch]} — all loss configs',\n"
    "                 fontsize=13, fontweight='bold')\n\n"
    "    for ax, split in zip(axes, ['clean','low','high']):\n"
    "        for loss_name in PHASE3_LOSS_KEYS:\n"
    "            run_name = f'phase3_{arch}_{loss_name}_{split}_s{SEEDS[0]}_e{EPOCHS}'\n"
    "            fpath = METRICS_DIR / run_name / 'pr_curve.json'\n"
    "            if not fpath.exists(): continue\n"
    "            d = _json.loads(fpath.read_text())\n"
    "            if not d.get('precision'): continue\n"
    "            prec = np.array(d['precision']); rec = np.array(d['recall'])\n"
    "            order = np.argsort(rec)\n"
    "            lw = 2.5 if 'aeiou' in loss_name else 1.5\n"
    "            ax.plot(rec[order], prec[order],\n"
    "                    color=PALETTE.get(loss_name,'#aaa'), lw=lw, alpha=0.85,\n"
    "                    label=f\"{LOSS_LABELS.get(loss_name,loss_name)} ({d.get('ap50',0):.3f})\")\n"
    "        ax.set_title(split, fontsize=11)\n"
    "        ax.set_xlabel('Recall'); ax.set_xlim(0,1); ax.set_ylim(0,1)\n"
    "        ax.grid(alpha=0.25)\n"
    "        ax.legend(fontsize=8, loc='lower left')\n\n"
    "    axes[0].set_ylabel('Precision')\n"
    "    plt.tight_layout()\n"
    "    _save = ANALYSIS_DIR / f'pr_curves_{arch}.png'\n"
    "    plt.savefig(_save, dpi=150, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    print(f'Saved -> {_save}')\n"
))

cells.append(code_cell(
    "# --- AP vs IoU threshold per architecture (clean split, all loss configs)\n"
    "import json as _json, numpy as np, matplotlib.pyplot as plt\n\n"
    "_iou_thresh = np.round(np.arange(0.5, 1.0, 0.05), 2)\n\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)\n"
    "fig.suptitle('AP vs IoU Threshold — clean split', fontsize=13, fontweight='bold')\n\n"
    "for ax, arch in zip(axes, ['yolo26s', 'rtdetr']):\n"
    "    for loss_name in PHASE3_LOSS_KEYS:\n"
    "        run_name = f'phase3_{arch}_{loss_name}_clean_s{SEEDS[0]}_e{EPOCHS}'\n"
    "        fpath = METRICS_DIR / run_name / 'pr_curve.json'\n"
    "        if not fpath.exists(): continue\n"
    "        d = _json.loads(fpath.read_text())\n"
    "        ap_arr = d.get('ap_per_iou_threshold')\n"
    "        if not ap_arr: continue\n"
    "        lw = 2.5 if 'aeiou' in loss_name else 1.5\n"
    "        ax.plot(_iou_thresh, ap_arr,\n"
    "                color=PALETTE.get(loss_name,'#aaa'), lw=lw, alpha=0.85,\n"
    "                marker='o', markersize=3,\n"
    "                label=LOSS_LABELS.get(loss_name, loss_name))\n"
    "    ax.set_title(_arch_labels[arch], fontsize=11)\n"
    "    ax.set_xlabel('IoU threshold'); ax.set_xticks(_iou_thresh)\n"
    "    ax.set_xticklabels([f'{t:.2f}' for t in _iou_thresh], fontsize=7, rotation=45)\n"
    "    ax.grid(alpha=0.3); ax.legend(fontsize=8, loc='upper right')\n\n"
    "axes[0].set_ylabel('Average Precision')\n"
    "plt.tight_layout()\n"
    "_save = ANALYSIS_DIR / 'ap_vs_iou_thresh_by_arch.png'\n"
    "plt.savefig(_save, dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved -> {_save}')\n"
))

cells.append(code_cell(
    "# --- COCO AP suite comparison table across architectures\n"
    "import json as _json, pandas as pd, numpy as np\n"
    "import matplotlib.pyplot as plt, seaborn as sns\n\n"
    "_metrics_list = ['map50_95','map50','map75','APs','APm','APl']\n"
    "_metric_labels = {'map50_95':'mAP50-95','map50':'mAP50','map75':'mAP75',\n"
    "                  'APs':'APs','APm':'APm','APl':'APl'}\n\n"
    "summary_rows = []\n"
    "for arch in ['yolo26s','rtdetr']:\n"
    "    for loss_name in PHASE3_LOSS_KEYS:\n"
    "        run_name = f'phase3_{arch}_{loss_name}_clean_s{SEEDS[0]}_e{EPOCHS}'\n"
    "        fpath = METRICS_DIR / run_name / 'coco_ap_suite.json'\n"
    "        if not fpath.exists(): continue\n"
    "        m = _json.loads(fpath.read_text())\n"
    "        row = {'arch': _arch_labels[arch], 'loss': LOSS_LABELS.get(loss_name, loss_name)}\n"
    "        row.update({k: m.get(k) for k in _metrics_list})\n"
    "        summary_rows.append(row)\n\n"
    "df_suite = pd.DataFrame(summary_rows)\n"
    "print('=== COCO AP Suite (clean split) ===')\n"
    "print(df_suite.to_string(index=False))\n"
    "df_suite.to_csv(ANALYSIS_DIR / 'coco_ap_suite_phase3.csv', index=False)\n\n"
    "# Heatmap: one per architecture\n"
    "for arch_label in df_suite['arch'].unique():\n"
    "    sub = df_suite[df_suite['arch'] == arch_label].set_index('loss')[_metrics_list]\n"
    "    sub.columns = [_metric_labels[c] for c in _metrics_list]\n"
    "    fig, ax = plt.subplots(figsize=(10, 5))\n"
    "    sns.heatmap(sub.astype(float), ax=ax, annot=True, fmt='.4f',\n"
    "                annot_kws={'size':9}, cmap='YlGn',\n"
    "                linewidths=0.4, cbar_kws={'shrink':0.7})\n"
    "    ax.set_title(f'COCO AP Suite — {arch_label} (clean split)', fontsize=12, fontweight='bold')\n"
    "    plt.tight_layout()\n"
    "    _fn = arch_label.lower().replace(' ','_').replace('-','_')\n"
    "    _save = ANALYSIS_DIR / f'coco_ap_{_fn}.png'\n"
    "    plt.savefig(_save, dpi=150, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    print(f'Saved -> {_save}')\n"
))

# ── 14. Final sync ────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 13 \u00b7 Persist & Sync"))

cells.append(code_cell(
    "# --- Save unified results + sync to Drive / summarise Kaggle output\n"
    "import shutil, json as _json\n\n"
    "# Save full results CSV\n"
    "df_all.to_csv(EXPERIMENTS / 'phase3_all_results.csv', index=False)\n\n"
    "# Final Drive sync (Colab)\n"
    "if DRIVE_AVAILABLE:\n"
    "    try:\n"
    "        shutil.copytree(str(EXPERIMENTS), str(DRIVE_EXPERIMENTS), dirs_exist_ok=True)\n"
    "        print(f'Synced to Drive: {DRIVE_EXPERIMENTS}')\n"
    "    except Exception as e:\n"
    "        print(f'Drive sync failed: {e}')\n"
    "else:\n"
    "    n_figs = len(list(ANALYSIS_DIR.glob('*.png')))\n"
    "    n_csvs = len(list(ANALYSIS_DIR.glob('*.csv')))\n"
    "    print(f'Phase 3 complete.')\n"
    "    print(f'  Figures: {n_figs} PNGs in {ANALYSIS_DIR}')\n"
    "    print(f'  Tables:  {n_csvs} CSVs')\n"
    "    print(f'  Download from Kaggle Output tab: amorphous-yolo/experiments_phase3/')\n"
))

# ── Build & save ─────────────────────────────────────────────────────────────
nb = {
    'nbformat': 4,
    'nbformat_minor': 5,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.10.0'},
        'kaggle': {'accelerator': 'GPU', 'isInternetEnabled': True,
                   'language': 'python', 'sourceType': 'notebook'},
    },
    'cells': cells,
}

with open('notebooks/06_phase3_cross_arch.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Saved: notebooks/06_phase3_cross_arch.ipynb  ({len(cells)} cells)")
